- job:
    name: ansible-role-logrotate
    run: tests/playbooks/run.yaml
    roles:
      - zuul: openstack/ansible-role-logrotate

- job:
    name: ansible-role-logrotate-fedora-27
    parent: ansible-role-logrotate
    nodeset: fedora-27

- job:
    name: ansible-role-logrotate-ubuntu-bionic
    parent: ansible-role-logrotate
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-logrotate-ubuntu-xenial
    parent: ansible-role-logrotate
    nodeset: ubuntu-xenial

- project:
    templates:
      - windmill-jobs-fedora-27
      - windmill-jobs-bionic
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-logrotate-fedora-27
        - ansible-role-logrotate-ubuntu-bionic
        - ansible-role-logrotate-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-logrotate-fedora-27
        - ansible-role-logrotate-ubuntu-bionic
        - ansible-role-logrotate-ubuntu-xenial
        - tox-linters
